# ***Numpy Exercise ***

Atharva Karekar

**NumPy Arrays:**

In [ ]:
import numpy as np

# Verify installation
print(np.__version__)


1.23.5


In [ ]:
import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3])
arr2 = np.arange(0, 10, 2)  # Array with elements from 0 to 8 with step 2

# Array indexing and slicing
print(arr1[0])
print(arr2[2:5])


1
[4 6 8]


**Data Types and Attributes**

In [ ]:
import numpy as np
arr1 = 5
arr2 = 4
# Mathematical operations
arr3 = arr1 + arr2
arr4 = np.square(arr1)

# Element-wise operations
arr5 = np.sin(arr1)

# Broadcasting
arr6 = arr1 * 2
print(arr3)
print(arr4)
print(arr5)
print(arr6)

9
25
-0.9589242746631385
10


In [ ]:
import numpy as np

# Data types
arr = np.array([1, 2, 3], dtype=np.float64)
print(arr.dtype)


float64


In [ ]:
import numpy as np

# Array attributes
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)


(2, 3)
6
2


***Universal Functions (ufuncs):***

In [ ]:
import numpy as np

# ufunc example
arr = np.array([1, 2, 3])
result = np.square(arr)
print(result)

[1 4 9]


In [ ]:
import numpy as np

# Common ufuncs
arr = np.array([1, 2, 3])
result1 = np.sqrt(arr)
result2 = np.exp(arr)
print(result1)
print(result2)

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]


**Array Manipulation:**


In [ ]:
import numpy as np

# Reshaping
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(arr)
print(reshaped_arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

# Stacking
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.stack((arr1, arr2))

# Splitting
split_arr = np.split(stacked_arr, 2)
print(split_arr)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


**Adding and removing elements:**

In [ ]:
import numpy as np

# Adding elements
arr = np.array([1, 2, 3])
new_arr = np.append(arr, 4)
print("Array after adding element:", new_arr)

# Removing elements
arr_without_last = np.delete(arr, -1)
print("Array after removing last element:", arr_without_last)


Array after adding element: [1 2 3 4]
Array after removing last element: [1 2]


**Indexing and Slicing:**

In [ ]:
import numpy as np

# Boolean indexing
arr = np.array([1, 2, 3, 4, 5])
bool_index = arr > 2
filtered_arr = arr[bool_index]
print("Array after boolean indexing:", filtered_arr)

# Fancy indexing
arr_indices = np.array([0, 2, 4])
selected_elements = arr[arr_indices]
print("Selected elements using fancy indexing:", selected_elements)


Array after boolean indexing: [3 4 5]
Selected elements using fancy indexing: [1 3 5]


In [ ]:
import numpy as np

# Slicing
arr = np.array([1, 2, 3, 4, 5])
sliced_arr = arr[1:4]
print("Sliced array:", sliced_arr)


Sliced array: [2 3 4]


**Linear Algebra with NumPy:**


In [ ]:
import numpy as np

# Matrix operations
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix1, matrix2)
print("Matrix product:\n", matrix_product)

# Inverse and determinant
inv_matrix1 = np.linalg.inv(matrix1)
det_matrix2 = np.linalg.det(matrix2)
print("Inverse of matrix1:\n", inv_matrix1)
print("Determinant of matrix2:", det_matrix2)


Matrix product:
 [[19 22]
 [43 50]]
Inverse of matrix1:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of matrix2: -2.000000000000005


In [ ]:
import numpy as np

# Solving linear equations
coeff_matrix = np.array([[2, 3], [4, 5]])
constants = np.array([10, 20])
solution = np.linalg.solve(coeff_matrix, constants)
print("Solution to linear equations:", solution)


Solution to linear equations: [5. 0.]


**Random in NumPy:**

In [ ]:
import numpy as np

# Generating random numbers
rand_num = np.random.rand()  # Random float between 0 and 1
rand_arr = np.random.randn(3, 3)  # Random array from standard normal distribution
print("Random number:", rand_num)
print("Random array:\n", rand_arr)

# Simulating random processes with NumPy:

import numpy as np

# Simulating random processes
random_walk = np.cumsum(np.random.choice([-1, 1], size=100))
print("Random walk simulation:", random_walk)


Random number: 0.28727926436184203
Random array:
 [[-0.37038755  0.56706952 -1.59914728]
 [ 0.95140024  2.54106788 -1.88419803]
 [ 1.18076182  0.57079348  0.1958417 ]]
Random walk simulation: [ 1  2  1  2  1  0  1  0 -1  0 -1  0  1  2  1  2  1  2  1  2  1  0  1  2
  3  2  3  4  5  4  5  6  7  8  9  8  7  8  7  6  7  6  5  4  5  6  5  4
  3  4  3  2  3  2  3  4  3  2  3  2  3  2  3  2  3  4  5  6  5  6  5  4
  3  2  3  2  1  2  1  2  3  4  5  6  7  6  7  8  7  6  5  4  3  4  3  2
  1  0 -1  0]


**Performance Optimization:**

In [ ]:
import numpy as np
import time

# Vectorized operation
arr1 = np.random.rand(1000000)
arr2 = np.random.rand(1000000)

# Using NumPy
start_time = time.time()
result = np.dot(arr1, arr2)
end_time = time.time()
print("Time taken with NumPy:", end_time - start_time)


Time taken with NumPy: 0.005915164947509766


Comparing performance with traditional Python lists:

In [ ]:
import time

# Using Python lists
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

# Without NumPy
start_time = time.time()
result = sum(i*j for i, j in zip(list1, list2))
end_time = time.time()
print("Time taken without NumPy:", end_time - start_time)


Time taken without NumPy: 0.23709678649902344


**NumPy and Data Science**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# Integration with pandas
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data)
print("DataFrame from NumPy array:\n", df)

# Integration with scikit-learn
X, y = np.arange(10).reshape((5, 2)), range(5)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print("Train and test sets:\n", X_train, X_test, y_train, y_test)


DataFrame from NumPy array:
    A  B
0  1  4
1  2  5
2  3  6
Train and test sets:
 [[0 1]
 [8 9]
 [6 7]
 [2 3]] [[4 5]] [0, 4, 3, 1] [2]


Examples of NumPy usage in real-world data analysis tasks:

In [ ]:
import numpy as np
import pandas as pd

# Data analysis example
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 22],
        'Salary': [50000, 60000, 45000]}

df = pd.DataFrame(data)
mean_salary = np.mean(df['Salary'])
print("Mean salary:", mean_salary)


Mean salary: 51666.666666666664
